import type { Metadata } from "next";
// @ts-ignore
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavBar } from "@/components/navbar/nav-bar";
import { inter, poppins } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* navbar for the site */}

          {/* main content */}
          <main className="relative mx-auto max-w-4xl">
            <NavBar />
            <div className="px-6 md:px-14">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
